{
 "title": "Public - UPerf Results",
 "tags": [
  "network ",
  "performance"
 ],
 "time": { "from": "2020-06-08T09:36:04.793Z", "to": "2020-06-08T17:31:32.817Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "cluster_name",
    "query": "{\"find\": \"terms\", \"field\": \"cluster_name.keyword\"}"
   },
   {
    "name": "user",
    "query": "{\"find\": \"terms\", \"field\": \"user.keyword\"}"
   },
   {
    "name": "iteration",
    "query": "{\"find\": \"terms\", \"field\": \"iteration\"}"
   },
   {
    "name": "server",
    "query": "{\"find\": \"terms\", \"field\": \"remote_ip.keyword\"}"
   },
   {
    "name": "test_type",
    "query": "{\"find\": \"terms\", \"field\": \"test_type.keyword\"}"
   },
   {
    "name": "protocol",
    "query": "{\"find\": \"terms\", \"field\": \"protocol.keyword\"}"
   },
   {
    "name": "message_size",
    "query": "{\"find\": \"terms\", \"field\": \"message_size\"}"
   },
   {
    "name": "threads",
    "query": "{\"find\": \"terms\", \"field\": \"num_threads\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "UPerf Performance : Throughput per-second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "uperf_ts", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "inlineScript": "_value * 8",
       "meta": {},
       "settings": { "script": { "inline": "_value * 8" } },
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND cluster_name: $cluster_name AND user: $user AND  iteration: $iteration AND remote_ip: $server AND message_size: $message_size AND test_type: $test_type AND protocol: $protocol AND num_threads: $threads",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "UPerf Performance : Operations per-second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uperf_ts",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "norm_ops",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND user: $user AND  iteration: $iteration AND remote_ip: $server AND message_size: $message_size AND test_type: $test_type AND protocol: $protocol AND num_threads: $threads",
     "timeField": "uperf_ts"
    }
   ]
  },
  {
   "title": "UPerf Result Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "test_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "protocol.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "num_threads",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "message_size",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "norm_byte",
       "id": "1",
       "inlineScript": "_value * 8",
       "meta": {},
       "settings": { "script": { "inline": "_value * 8" } },
       "type": "avg"
      },
      {
       "field": "norm_ops",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "norm_ltcy",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      { "field": "select field", "id": "8", "type": "count" }
     ],
     "query": "uuid: $uuid AND user: $user AND  iteration: $iteration AND remote_ip: $server AND message_size: $message_size AND test_type: $test_type AND protocol: $protocol AND NOT norm_ops:0",
     "timeField": "uperf_ts"
    }
   ]
  }
 ]
}