{
 "title": "etcd-cluster-info",
 "description": "Etcd Dashboard from Prometheus for clusters running etcd as Kubernetes Pods",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({job=\"$cluster\"}, pod)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"$cluster\"}, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({job=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod_ip",
    "label": "PodIp",
    "query": "label_values(kube_pod_info{pod=\"$pod\" }, pod_ip)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\",job=~\"$cluster\"}"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Etcd Members",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(etcd_server_id{pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "members"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  { "title": "DB Info per Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "% DB Space Used $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "repeat": "pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "% DB Space Used $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "% DB Space Used $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "DB Left capacity (with fragmented space) $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "repeat": "pod",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "Backend bytes - DB Size"
    }
   ]
  },
  {
   "title": "DB Left capacity (with fragmented space) $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "Backend bytes - DB Size"
    }
   ]
  },
  {
   "title": "DB Left capacity (with fragmented space) $pod",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "Backend bytes - DB Size"
    }
   ]
  },
  {
   "title": "DB Size Limit (Backend-bytes) $pod",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "repeat": "pod",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Quota Bytes"
    }
   ]
  },
  {
   "title": "DB Size Limit (Backend-bytes) $pod",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Quota Bytes"
    }
   ]
  },
  {
   "title": "DB Size Limit (Backend-bytes) $pod",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Quota Bytes"
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Num keys"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} heartbeat  failures"
    },
    {
     "expr": "etcd_server_health_failures{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} health failures"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} slow applies"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} slow read indexes"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_put_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} puts/s"
    },
    {
     "expr": "rate(etcd_debugging_mvcc_delete_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} deletes/s"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod  }} keys compacted "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Resident Memory"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Used bytes"
    }
   ]
  }
 ]
}