{
 "title": "OpenShift Cluster Performance Dashboard",
 "description": "Performance dashboards for Red Hat OpenShift",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "_node",
    "label": "masters",
    "query": "query_result(  kube_node_role{role=\"master\"} )"
   },
   {
    "name": "_worker_node",
    "label": "worker",
    "query": "query_result(  kube_node_role{role=\"worker\"} )"
   },
   {
    "name": "_infra_node",
    "label": "infra",
    "query": "query_result(  kube_node_role{role=\"infra\"} )"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "block_device",
    "label": "Block Device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   },
   {
    "name": "clustername",
    "query": "label_values(process_cpu_seconds_total,clustername)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubelet CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"kubelet\",job=\"kubelet\"}[5m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "crio CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"kubelet\",job=\"crio\"}[5m])",
     "legendFormat": "crio - {{instance}}"
    }
   ]
  },
  {
   "title": "Kubelet Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"kubelet\",job=\"kubelet\"}",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "crio Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"kubelet\",job=\"crio\"}",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  },
  {
   "title": "kube-proxy Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(kubeproxy_sync_proxy_rules_duration_seconds_sum[2m])/rate(kubeproxy_sync_proxy_rules_duration_seconds_count[2m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{namespace!=\"\"})",
       "legendFormat": "{{namespace}} - {{name}}"
      }
     ]
    },
    {
     "title": "400/500 requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 * sum by(service,job) (rate(rest_client_requests_total{code=~\"4..\",clustername=\"$clustername\"}[5m])) / sum by(service,job) (rate(rest_client_requests_total{clustername=\"$clustername\"}[5m]))",
       "legendFormat": "400s : {{service}} -  {{job}} "
      },
      {
       "expr": "100 * sum by(service,job) (rate(rest_client_requests_total{code=~\"5..\",clustername=\"$clustername\"}[5m])) / sum by(service,job) (rate(rest_client_requests_total{clustername=\"$clustername\"}[5m]))",
       "legendFormat": "500s : {{service}} -  {{job}} "
      }
     ]
    },
    {
     "title": "API Request Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,service) (rate(apiserver_request_count{clustername=~\"$clustername\"}[5m]))",
       "legendFormat": "{{service}} - {{instance}}"
      }
     ]
    },
    {
     "title": "API Requests per client",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(rate(apiserver_request_count{resource=\"pods\"}[3m]))",
       "legendFormat": "{{client}} - {{verb}}"
      }
     ]
    },
    {
     "title": "Number of nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_info{clustername=~\"$clustername\"})",
       "legendFormat": "Number of nodes"
      }
     ]
    },
    {
     "title": "Goroutines Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(go_goroutines{clustername=~\"$clustername\"}) by (job,instance))",
       "legendFormat": "{{job}} - {{instance}}"
      }
     ]
    },
    {
     "title": "pod count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\",clustername=~\"$clustername\"})",
       "legendFormat": "Running Pods"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\",clustername=~\"$clustername\"})",
       "legendFormat": "Succeeded Pods"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\",clustername=~\"$clustername\"})",
       "legendFormat": "Failed Pods"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Pending\",clustername=~\"$clustername\"})",
       "legendFormat": "Pending Pods"
      }
     ]
    },
    {
     "title": "Namespace Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_namespace_created{clustername=~\"$clustername\"})",
       "legendFormat": "Namespace Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Master : $_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic : $_node",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "System Memory : $_node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",} + node_memory_Buffers_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\",} - (node_memory_Cached_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"} + node_memory_Buffers_bytes{instance=~\"$_node\",job=~\".*\",clustername=~\"$clustername\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk Throughput : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\",}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Network Utilization : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets/s : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Container CPU Usage : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{name!=\"\",node=~\"$_node\",clustername=~\"$clustername\",namespace!=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{ namespace }} - {{name}} - {{ service }}"
      }
     ]
    },
    {
     "title": "Process RSS :$_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(container_memory_rss{name!=\"\",node=~\"$_node\",clustername=~\"$clustername\",namespace!=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{namespace}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker $_worker_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "_worker_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic : $_node",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}[1m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "System Memory : $_node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\",} + node_memory_Buffers_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\",}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\",} - (node_memory_Cached_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"} + node_memory_Buffers_bytes{instance=~\"$_worker_node\",job=~\".*\",clustername=~\"$clustername\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk Throughput : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_worker_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_worker_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS : $_node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_worker_node\",clustername=~\"$clustername\",}[1m])",
       "legendFormat": "{{instance}} - {{device}} - read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_worker_node\",clustername=~\"$clustername\"}[1m])",
       "legendFormat": "{{instance}} - {{device}} - write"
      }
     ]
    },
    {
     "title": "Network Utilization : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$_worker_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$_worker_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets/s : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$_worker_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$_worker_node\",device=~\"$net_device\",clustername=~\"$clustername\"}[1m]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Container CPU Usage : $_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{name!=\"\",node=~\"$_worker_node\",clustername=~\"$clustername\",namespace!=\"\",namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{ namespace }} - {{name}} - {{ service }}"
      }
     ]
    },
    {
     "title": "Process RSS :$_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{name!=\"\",node=~\"$_worker_node\",clustername=~\"$clustername\",namespace!=\"\",namespace=~\"$namespace\"}",
       "legendFormat": "{{namespace}} - {{name}}"
      }
     ]
    }
   ]
  }
 ]
}